JCC = javac

JFLAGS = 
CLASSES = ./src/main/java/pt/ulisboa/tecnico/meic/cnv/mazerunner/maze/*.java ./src/main/java/pt/ulisboa/tecnico/meic/cnv/mazerunner/maze/render/*.java ./src/main/java/pt/ulisboa/tecnico/meic/cnv/mazerunner/maze/strategies/*.java ./src/main/java/pt/ulisboa/tecnico/meic/cnv/mazerunner/maze/exceptions/*.java


all:
	$(JAVAC) $(JFLAGS) $(CLASSES)


clean:
	find -name "*.class" -delete
